-- AlterTable
ALTER TABLE "appointments" ALTER COLUMN "starts_at" SET DATA TYPE TIMESTAMPTZ(3),
ALTER COLUMN "ends_at" SET DATA TYPE TIMESTAMPTZ(3),
ALTER COLUMN "cancelled_at" SET DATA TYPE TIMESTAMPTZ(3),
ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMPTZ(3);

-- AlterTable
ALTER TABLE "time_off" ALTER COLUMN "starts_at" SET DATA TYPE TIMESTAMPTZ(3),
ALTER COLUMN "ends_at" SET DATA TYPE TIMESTAMPTZ(3);

-- AlterTable
ALTER TABLE "users" ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMPTZ(3);
